#!/usr/bin/env bash
module load foss/2022a
module load GCC/11.3.0
module load CUDA/11.7.0
module load GCCcore/11.3.0; module load Python/3.10.4

# check it exist! mkdir /data/gpfs/projects/punim2039/envs
virtualenv ~/venvs/nlp_gpu/
source ~/venvs/nlp_gpu/bin/activate

