#!/usr/bin/env bash
module load foss/2022a
module load GCC/11.3.0
module load CUDA/11.7.0
module load GCCcore/11.3.0; module load Python/3.10.4

# check it exist! mkdir /data/gpfs/projects/punim2039/envs
virtualenv ~/venvs/nlp_gpu/
source ~/venvs/nlp_gpu/bin/activate

pip install --upgrade pip==23.1.2
pip install six==1.15.0
pip install 'requests>=2.21.0,<3'
pip install pandas==1.2.0
pip install didipack
pip install beautifulsoup4==4.12.2
pip install transformers==4.30.2
pip install html2text==2020.1.16
pip install 'urllib3<2.0'
pip install wrds==3.1.6
pip install nltk==3.8.1
pip install xlrd
pip install openpyxl
pip install seaborn
pip install pandarallel==1.6.5
pip install yfinance
pip install nltk==3.8.1
pip install transformers

