#!/usr/bin/env bash
pip install --upgrade pip==23.1.2
pip install numpy==1.22.3
pip install pandas==1.4.2
pip install six==1.15.0
pip install 'requests>=2.21.0,<3'
pip install didipack
pip install beautifulsoup4==4.12.2
pip install transformers==4.30.2
pip install html2text==2020.1.16
pip install 'urllib3<2.0'
pip install wrds==3.1.6
pip install nltk==3.8.1
pip install xlrd
pip install openpyxl
pip install seaborn
pip install pandarallel==1.6.5
pip install yfinance
pip install nltk==3.8.1
pip install transformers
pip install pyperclip
pip install torch

# if not through local modules!
pip install tensorflow==2.11.0

#ssh ADIDISHEIM@vm-172-26-151-115.desktop.cloud.unimelb.edu.au
